substitutions:
  _SERVICE_NAME: app-template
  _REGION: europe-west1

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}
      - --region=${_REGION}
      - --platform=managed
      - --project=$PROJECT_ID
      - --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}
